#if !canImport(ObjectiveC)
import XCTest

extension SHA1Tests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SHA1Tests = [
        ("testSHA1", testSHA1),
        ("testSHA1Array", testSHA1Array),
        ("testSHA1ArrayExtension", testSHA1ArrayExtension),
        ("testSHA1String", testSHA1String),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SHA1Tests.__allTests__SHA1Tests),
    ]
}
#endif
