#if !canImport(ObjectiveC)
import XCTest

extension UInt24Tests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UInt24Tests = [
        ("testBytesSwapped", testBytesSwapped),
        ("testDescription", testDescription),
        ("testUInt24", testUInt24),
        ("testUInt24Max", testUInt24Max),
        ("testUInt24Overflow", testUInt24Overflow),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UInt24Tests.__allTests__UInt24Tests),
    ]
}
#endif
