#if !canImport(ObjectiveC)
import XCTest

extension X509DecodeTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__X509DecodeTests = [
        ("testIdentifier", testIdentifier),
        ("testSerialNumber", testSerialNumber),
        ("testValidity", testValidity),
        ("testVersion", testVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(X509DecodeTests.__allTests__X509DecodeTests),
    ]
}
#endif
