#if !canImport(ObjectiveC)
import XCTest

extension ASN1DecodeTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ASN1DecodeTests = [
        ("testContentBoolean", testContentBoolean),
        ("testContentData", testContentData),
        ("testContentEnumerated", testContentEnumerated),
        ("testContentObjectIdentifier", testContentObjectIdentifier),
        ("testContentPrintableString", testContentPrintableString),
        ("testContentSequence", testContentSequence),
        ("testContentUTF8String", testContentUTF8String),
        ("testContextSpecificEndOfContent", testContextSpecificEndOfContent),
        ("testUniversalSequence", testUniversalSequence),
    ]
}

extension ASN1EncodeTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ASN1EncodeTests = [
        ("testContentBoolean", testContentBoolean),
        ("testContentData", testContentData),
        ("testContentEnumerated", testContentEnumerated),
        ("testContentPrintableString", testContentPrintableString),
        ("testContentSequence", testContentSequence),
        ("testContentUTF8String", testContentUTF8String),
        ("testContextSpecificEndOfContent", testContextSpecificEndOfContent),
        ("testUniversalSequence", testUniversalSequence),
    ]
}

extension ASN1LengthTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ASN1LengthTests = [
        ("testReadLength1Octet", testReadLength1Octet),
        ("testReadLength2Octets", testReadLength2Octets),
        ("testReadLength4Octets", testReadLength4Octets),
    ]
}

extension ASN1Tests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ASN1Tests = [
        ("testEqualityBug", testEqualityBug),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ASN1DecodeTests.__allTests__ASN1DecodeTests),
        testCase(ASN1EncodeTests.__allTests__ASN1EncodeTests),
        testCase(ASN1LengthTests.__allTests__ASN1LengthTests),
        testCase(ASN1Tests.__allTests__ASN1Tests),
    ]
}
#endif
