#if !canImport(ObjectiveC)
import XCTest

extension UUIDTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UUIDTests = [
        ("testDecodeUUIDString", testDecodeUUIDString),
        ("testEncodeUUIDString", testEncodeUUIDString),
        ("testNamespace", testNamespace),
        ("testUUID", testUUID),
        ("testUUIDv5", testUUIDv5),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UUIDTests.__allTests__UUIDTests),
    ]
}
#endif
